flasktaskr/models.py
# models.py


# Core Python Imports
import datetime

# App Specific Imports
from flasktaskr import app, db

# Third Party Imports
from itsdangerous import (TimedJSONWebSignatureSerializer
                          as Serializer, BadSignature, SignatureExpired)


class User(db.Model):
    """
    DocString
    """

    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, unique=True, nullable=False)
    email = db.Column(db.String, unique=True, nullable=False)
    password = db.Column(db.String, nullable=False)
    is_active = db.Column(db.Integer, default=0)
    is_admin = db.Column(db.Integer, default=0)
    tasks = db.relationship('Task', backref='poster', lazy='dynamic')
    date_added = db.Column(db.DateTime(timezone=True), default=datetime.datetime.now())
    date_modified = db.Column(db.DateTime(timezone=True), default=datetime.datetime.now())

    def __init__(self, name, email, password):
        self.name = name
        self.email = email
        self.password = password

    def generate_auth_token(self, expiration=14400):
        s = Serializer(app.config['SECRET_KEY'], expires_in=expiration)
        return s.dumps({'id': self.id})


    @staticmethod
    def verify_auth_token(token):
        s = Serializer(app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except SignatureExpired:
            return None # valid token, but expired
        except BadSignature:
            return None # invalid token
        user = User.query.get(data['id'])
        user.id = data['id']
        return user


    def __repr__(self):
        return '<id: {}>, <username: {}>'.format(self.id, self.name)


class Task(db.Model):
    """
    DocString
    """

    __tablename__ = 'tasks'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)
    due_date = db.Column(db.Date, nullable=False)
    priority = db.Column(db.Integer, nullable=False)
    status = db.Column(db.Integer, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    date_added = db.Column(db.DateTime(timezone=True), default=datetime.datetime.now())
    date_modified = db.Column(db.DateTime(timezone=True), default=datetime.datetime.now())

    def __repr__(self):
        return '<name: {}>'.format(self.name)

flasktaskr/tasks/forms.py
# forms.py

# Flask related imports
from flask_wtf import Form
from wtforms import StringField, DateField, IntegerField, SelectField
from wtforms.validators import DataRequired


class AddTaskForm(Form):
    """
    DocString
    """

    task_id = IntegerField()
    name = StringField('Task Name', validators=[DataRequired()])
    due_date = DateField (
        'Date Due (mm/dd/yyyy)',
        validators=[DataRequired()],
        format='%m%d%Y'
    )
    priority = SelectField (
        'Priority',
        validators=[DataRequired()],
        choices=[
            ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), \
                    ('6', '6'), ('7', '7'), ('8', '8'), \
                    ('9', '9'), ('10', '10')
        ]
    )
    status = IntegerField('Status')

flasktaskr/users/forms.py
# users/forms.py

# Flask third party imports
from flask_wtf import Form
from wtforms import StringField, DateField, IntegerField, SelectField, \
        PasswordField
from wtforms.validators import DataRequired, EqualTo, Length


class RegisterForm(Form):
    """
    DocString
    """

    name = StringField('Username',
        validators=[DataRequired(), Length(min=6, max=25)]
    )
    email = StringField('Email',
        validators=[DataRequired(), Length(min=6, max=40)]
    )
    password = PasswordField('Password',
        validators=[DataRequired(), Length(min=6, max=40)]
    )
    confirm = PasswordField('Confirm Password',
        validators=[DataRequired(),
        EqualTo('password', message="Passwords must match")]
    )


class LoginForm(Form):
    """
    DocString
    """

    name = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])

flasktaskr/__init__.py
# flasktaskr/__init__.py

# Core Python Imports
import os

# Flask related imports
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_httpauth import HTTPBasicAuth

app = Flask(__name__)
app.config.from_object(os.environ['APP_SETTINGS'])
bcrypt = Bcrypt(app)
auth = HTTPBasicAuth()
db = SQLAlchemy(app)

from flasktaskr.users.views import users_blueprint
from flasktaskr.tasks.views import tasks_blueprint

# register our blueprints
app.register_blueprint(users_blueprint)
app.register_blueprint(tasks_blueprint)

flasktaskr/tasks/views.py
# tasks/views.py

###############
### Imports ###
###############

# Core Python Imports
import datetime
from functools import wraps

# Flask Imports
from flask import Blueprint, request, g

# Flask Third party imports
from flask_restful import Resource, Api, reqparse, fields, marshal

# App Specific Imports
from flasktaskr import db
from flasktaskr.models import Task, User


#########################
### Blueprints config ###
#########################

tasks_blueprint = Blueprint('tasks', __name__)
tasks = Api(tasks_blueprint)


# validate token decorator
def validate_token(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        auth_token = request.headers.get('X-auth-token')
        if not auth_token:
            return {
                'success': 'false',
                'message': 'Token not found.'
            }
        else:
            user = User.verify_auth_token(auth_token)
            if not user:
                return {
                    'success': 'false',
                    'message': 'Invalid Token.'
                }
            else:
                g.user = user
                return f(*args, **kwargs)
    return wrap


# Fields to be serialized

task_resource_fields = {
    'name': fields.String,
    'due_date': fields.String,
    'priority': fields.Integer,
    'status': fields.Integer,
    'user_id': fields.Integer,
    'date_added': fields.DateTime,
    'date_modified': fields.DateTime
}

user_resource_fields = {
    'name': fields.String,
    'id': fields.Integer,
    'password': fields.String
}


# Resources

class AllTasks(Resource):
    """
    Returns all tasks
    """

    @validate_token
    def get(self, status_id):

        # get tasks based on status_id
        tasks = Task.query.filter_by(status=status_id).all()

        if not tasks:
            return {
                'success': 'false',
                'message': 'No tasks found.'
            }

        else:
            return {
                'success': 'true',
                'data': marshal(tasks, task_resource_fields)
            }


class Tasks(Resource):
    """
    Single Task Resource
    """

    def get(self, task_id):

        # check for task_id
        if not task_id:
            return {
                'success': 'false',
                'message': 'No task id specified.'
            }

        else:
            try:

                # get a single task
                task = Task.query.get_or_404(task_id)
                return {
                    'success': 'true',
                    'data': marshal(task, task_resource_fields)
                }
            except Exception as e:
                return {
                    'success': 'false',
                    'message': '{}'.format(e)
                }


    @validate_token
    def post(self):

        # instantiate reqparse object
        parser = reqparse.RequestParser()

        # payload data sanity check
        parser.add_argument('name', required=True, \
                location='form')
        parser.add_argument('due_date', required=True, \
                location='form')
        parser.add_argument('priority', required=True, type=int, \
                location='form')

        # creating args object
        args = parser.parse_args(strict=True)

        # create a new task
        try:
            # create new task object to be inserted
            task = Task(
                name=args['name'],
                due_date=args['due_date'],
                priority=int(args['priority']),
                status=1,
                user_id=User.poster,
                date_added=datetime.datetime.now(),
                date_modified=datetime.datetime.now()
            )

            # insert the new task
            db.session.add(task)

            # commit the changes
            db.session.commit()

            return {
                'success': 'true',
                'message': 'New task inserted.',
                'data': marshal(task, task_resource_fields)
            }, 201

        except Exception as e:
            return {
                'success': 'false',
                'message': '{}'.format(e)
            }

    def put(self):

        # instantiate reqparse object
        parser = reqparse.RequestParser()

        # payload data sanity check
        parser.add_argument('task_id', required=True, type=int,
                            location='form', help="Task ID is required")

        # create the args object
        args = parser.parse_args(strict=True)

        try:

            # get the appropriate task
            task = Task.query.get_or_404(args['task_id'])

            # set the task staus as closed
            task.status = 2

            # update date modified
            task.date_modified = datetime.datetime.now()

            # add the changes to the session
            db.session.add(task)

            # commit the changes to the db
            db.session.commit()

            return {
                'success': 'true',
                'message': 'Task updated successfully.',
                'data': marshal(task, resource_fields)
            }

        except Exception as e:
            return {
                'success': 'false',
                'message': '{}'.format(e)
            }

    def delete(self):

        # instantiate the reqparse object
        parser = reqparse.RequestParser()

        # payload data sanity check
        parser.add_argument('task_id', required=True, type=int,
                            location='form', help="Task ID is required")

        # create the args object
        args = parser.parse_args(strict=True)

        try:

            # get the appropriate task
            task = Task.query.get_or_404(args['task_id'])

            # delete the row from db
            db.session.delete(task)

            # commit the changes to the db
            db.session.commit()

            return {
                'success': 'true',
                'message': 'Task successfully deleted.'
            }

        except Exception as e:
            return {
                'success': 'false',
                'message': '{}'.format(e)
            }


# bind the resource to a route
tasks.add_resource(AllTasks, '/api/v1/tasks/<int:status_id>')
tasks.add_resource(Tasks, '/api/v1/task', '/api/v1/task/<int:task_id>')

flasktaskr/users/views.py
# users/views.py

###############
### Imports ###
###############

# Core Python Imports
import datetime, time, codecs, base64
from functools import wraps

# Flask Imports
from flask import Blueprint, request

# Flask Third party Imports
from sqlalchemy.exc import IntegrityError
from flask_restful import Resource, Api, fields, marshal, reqparse

# App Specific Imports
from flasktaskr import db, bcrypt, auth
from flasktaskr.models import User


##############
### config ###
##############

users_blueprint = Blueprint('users', __name__)
users = Api(users_blueprint)


# user data to be serailized

user_post_resource_fields = {
    'name': fields.String
}

# Resources

class Users(Resource):
    """
    Resource for Users
    """

    def post(self):
        
        # instantiate the reqparse object
        parser = reqparse.RequestParser()

        # payload data sanity check
        parser.add_argument('name', type=str, location='form', \
                help='Name is a required field.')
        parser.add_argument('email', type=str, required=True, \
                location='form', help='Email is required field.')
        parser.add_argument('password', type=str, required=True, \
                location='form', help='Password is a required field.')

        # create the args object
        args = parser.parse_args(strict=True)
        
        # create the user object to be inserted
        user = User(
            args['name'],
            args['email'],
            bcrypt.generate_password_hash(args['password'])
        )

        # check if user is already registered
        user_exists = User.query.filter_by(email=args['email']).first()
        if not user_exists:
            try:
                # add the object
                db.session.add(user)

                # commit the changes
                db.session.commit()

                return {
                    'success': 'true',
                    'data': marshal(user, user_post_resource_fields)
                }, 201

            except IntegrityError:
                return {
                    'success': 'false',
                    'message': 'User already exists.'
                }
        else:
            return {
                'success': 'false',
                'message': 'User already exists.'
            }


class Token(Resource):
    """
    Generates Auth Token for users
    """

    def post(self):

        # get the user from db
        user = User.query.filter_by(email=request.authorization.username).first()
        if not user:
            return {
                    'success': 'false',
                    'message': 'User not found.'
            }
        else:
            if user.password.startswith(r'\x'):
                user.password = codecs.decode(bytes(user.password[2:], \
                            'ascii'), 'hex')
            # verify password
            if bcrypt.check_password_hash(user.password, \
                    request.authorization.password):
                # generate auth token
                auth_token = user.generate_auth_token()
                return {
                    'token': auth_token.decode('ascii')
                }


# Bind the resources to routes
users.add_resource(Users, '/api/v1/user')
users.add_resource(Token, '/api/v1/token')

flasktaskr/templates/_base.html
<!DOCTYPE html>
<html >
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>FlaskTaskr</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- CSS Includes -->
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
    </head>
    <body>
      <div class="page">
        <!-- Flash Messages -->
        {% for message in get_flashed_messages() %}
          <div class="flash">{{ message }}</div>
        {% endfor %}
        <!-- Error -->
        {% if error %}
          <div class="error"><strong>Error: </strong>{{ error }}</div>
        {% endif %}
        <br>
        <h1>Welcome to FlaskTaskr</h1>
        {% block content %}
        {% endblock %}
      </div>
    </body>
</html>

flasktaskr/templates/login.html
{% extends "_base.html" %}
{% block content %}

<h3>Please Login to access your task list.</h3>
<form method="post" action="{{ url_for('users.login') }}">
  {{ form.csrf_token }}
  <span>Username: <input type="text" name="name" value="{{ request.form.name }}"></input></span>
  <span>Password: <input type="password" name="password" value="{{ request.form.password }}"></input></span>
  <input type="submit" name="Login" value="Login"></input>
</form>

<br>

<p><em>Need an account?</em><a href="{{ url_for('users.register') }}"> Signup!!</a></p>

{% endblock %}

flasktaskr/templates/register.html
{% extends "_base.html" %}
{% block content %}

<h3>Please register to access the task list.</h3>
  <form method="POST" action="/register">
    {{ form.csrf_token }}
    <p>
      {{ form.name.label }}: {{ form.name }}
      {{ form.email.label }}: {{ form.email }}
    </p>
    <p>
      {{ form.password.label }}: {{ form.password }}
      &nbsp;&nbsp;
      {{ form.confirm.label }}: {{ form.confirm }}
    </p>
    <p>
      <input type="submit" value="Register"></input>
    </p>
  </form>

  <br>

  <p><em>Already registered?</em> Click <a href="{{ url_for('users.login') }}">here</a> to login.</p>

{% endblock %}

flasktaskr/templates/tasks.html
{% extends "_base.html" %}
{% block content %}

<a href="/logout">Logout</a>
<div class="add-task">
  <h3>Add a new task:</h3>
  <form method="post" action="{{ url_for('tasks.new_task') }}">
    {{ form.csrf_token }}
    <p>
      {{ form.name.label }}: {{ form.name }}<br>
      {{ form.due_date.label }}: {{ form.due_date }}<br>
      {{ form.priority.label }}: {{ form.priority }}<br>
    </p>
    <p><input class="button" type="submit" value="Save"></p>
  </form>
</div>

<div class="entries">
  <br>
  <br>
  <h2>Open tasks:</h2>
  <div class="datagrid">
    <table>
      <thead>
        <tr>
          <th width="300px"><strong>Task Name</strong></th>
          <th width="100px"><strong>Due Date</strong></th>
          <th width="100px"><strong>Posted Date</strong></th>
          <th width="50px"><strong>Priority</strong></th>
          <th width="50px"><strong>Posted By</strong></th>
          <th><strong>Actions</strong></th>
        </tr>
      </thead>
      {% for task in open_tasks %}
        <tr>
          <td width="300px">{{ task.name }}</td>
          <td width="100px">{{ task.due_date }}</td>
          <td width="100px">{{ task.date_modified }}</td>
          <td width="50px">{{ task.priority }}</td>
          <td width="100px">{{ task.poster.name }}</td>
          <td>
          <p>
            <span>
              <a href="{{ url_for('tasks.delete', task_id =task.task_id) }}">Delete</a>
            </span>
            <span>
              <a href="{{ url_for('tasks.complete', task_id = task.task_id)}}">Mark as Complete</a>
            </span>
          </p>
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>
  <br>
  <br>
</div>

<div class="entries">
  <h2>Closed tasks:</h2>
  <div class="datagrid">
    <table>
      <thead>
        <tr>
          <th width="300px"><strong>Task Name</strong></th>
          <th width="100px"><strong>Due Date</strong></th>
          <th width="100px"><strong>Posted Date</strong></th>
          <th width="50px"><strong>Priority</strong></th>
          <th width="50px"><strong>Posted By</strong></th>
          <th><strong>Actions</strong></th>
        </tr>
      </thead>
      {% for task in closed_tasks %}
        <tr>
          <td width="300px">{{ task.name }}</td>
          <td width="100px">{{ task.due_date }}</td>
          <td width="100px">{{ task.date_modified }}</td>
          <td width="50px">{{ task.priority }}</td>
          <td width="100px">{{ task.poster.name }}</td>
          <td>
            <a href="{{ url_for('tasks.delete', task_id =
            task.task_id) }}">Delete</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>
</div>

{% endblock %}